// language-data.js
// 完整 i18n 語言列表，支援搜尋篩選

const languageData = [
  // === 常用語言 (置頂) ===
  { code: 'zh-TW', name: '繁體中文', localName: 'Traditional Chinese', isFavorite: true },
  { code: 'zh-CN', name: '简体中文', localName: 'Simplified Chinese', isFavorite: true },
  { code: 'en', name: 'English', localName: 'English', isFavorite: true },
  { code: 'ja', name: '日本語', localName: 'Japanese', isFavorite: true },
  { code: 'ko', name: '한국어', localName: 'Korean', isFavorite: true },
  // === 完整列表 (字母排序) ===
  { code: 'af', name: 'Afrikaans', localName: 'Afrikaans' },
  { code: 'sq', name: 'Shqip', localName: 'Albanian' },
  { code: 'am', name: 'አማርኛ', localName: 'Amharic' },
  { code: 'ar', name: 'العربية', localName: 'Arabic' },
  { code: 'hy', name: 'Հայերեն', localName: 'Armenian' },
  { code: 'az', name: 'Azərbaycan', localName: 'Azerbaijani' },
  { code: 'eu', name: 'Euskara', localName: 'Basque' },
  { code: 'be', name: 'Беларуская', localName: 'Belarusian' },
  { code: 'bn', name: 'বাংলা', localName: 'Bengali' },
  { code: 'bs', name: 'Bosanski', localName: 'Bosnian' },
  { code: 'bg', name: 'Български', localName: 'Bulgarian' },
  { code: 'my', name: 'မြန်မာ', localName: 'Burmese' },
  { code: 'ca', name: 'Català', localName: 'Catalan' },
  { code: 'ceb', name: 'Cebuano', localName: 'Cebuano' },
  { code: 'hr', name: 'Hrvatski', localName: 'Croatian' },
  { code: 'cs', name: 'Čeština', localName: 'Czech' },
  { code: 'da', name: 'Dansk', localName: 'Danish' },
  { code: 'nl', name: 'Nederlands', localName: 'Dutch' },
  { code: 'et', name: 'Eesti', localName: 'Estonian' },
  { code: 'fi', name: 'Suomi', localName: 'Finnish' },
  { code: 'fr', name: 'Français', localName: 'French' },
  { code: 'gl', name: 'Galego', localName: 'Galician' },
  { code: 'ka', name: 'ქართული', localName: 'Georgian' },
  { code: 'de', name: 'Deutsch', localName: 'German' },
  { code: 'el', name: 'Ελληνικά', localName: 'Greek' },
  { code: 'gu', name: 'ગુજરાતી', localName: 'Gujarati' },
  { code: 'ht', name: 'Kreyòl Ayisyen', localName: 'Haitian Creole' },
  { code: 'ha', name: 'Hausa', localName: 'Hausa' },
  { code: 'he', name: 'עברית', localName: 'Hebrew' },
  { code: 'hi', name: 'हिन्दी', localName: 'Hindi' },
  { code: 'hu', name: 'Magyar', localName: 'Hungarian' },
  { code: 'is', name: 'Íslenska', localName: 'Icelandic' },
  { code: 'ig', name: 'Igbo', localName: 'Igbo' },
  { code: 'id', name: 'Bahasa Indonesia', localName: 'Indonesian' },
  { code: 'ga', name: 'Gaeilge', localName: 'Irish' },
  { code: 'it', name: 'Italiano', localName: 'Italian' },
  { code: 'jv', name: 'Basa Jawa', localName: 'Javanese' },
  { code: 'kn', name: 'ಕನ್ನಡ', localName: 'Kannada' },
  { code: 'kk', name: 'Қазақ', localName: 'Kazakh' },
  { code: 'km', name: 'ខ្មែរ', localName: 'Khmer' },
  { code: 'rw', name: 'Kinyarwanda', localName: 'Kinyarwanda' },
  { code: 'ku', name: 'Kurdî', localName: 'Kurdish' },
  { code: 'ky', name: 'Кыргызча', localName: 'Kyrgyz' },
  { code: 'lo', name: 'ລາວ', localName: 'Lao' },
  { code: 'la', name: 'Latina', localName: 'Latin' },
  { code: 'lv', name: 'Latviešu', localName: 'Latvian' },
  { code: 'lt', name: 'Lietuvių', localName: 'Lithuanian' },
  { code: 'lb', name: 'Lëtzebuergesch', localName: 'Luxembourgish' },
  { code: 'mk', name: 'Македонски', localName: 'Macedonian' },
  { code: 'mg', name: 'Malagasy', localName: 'Malagasy' },
  { code: 'ms', name: 'Bahasa Melayu', localName: 'Malay' },
  { code: 'ml', name: 'മലയാളം', localName: 'Malayalam' },
  { code: 'mt', name: 'Malti', localName: 'Maltese' },
  { code: 'mi', name: 'Māori', localName: 'Maori' },
  { code: 'mr', name: 'मराठी', localName: 'Marathi' },
  { code: 'mn', name: 'Монгол', localName: 'Mongolian' },
  { code: 'ne', name: 'नेपाली', localName: 'Nepali' },
  { code: 'no', name: 'Norsk', localName: 'Norwegian' },
  { code: 'ny', name: 'Chichewa', localName: 'Nyanja' },
  { code: 'or', name: 'ଓଡ଼ିଆ', localName: 'Odia' },
  { code: 'ps', name: 'پښتو', localName: 'Pashto' },
  { code: 'fa', name: 'فارسی', localName: 'Persian' },
  { code: 'pl', name: 'Polski', localName: 'Polish' },
  { code: 'pt', name: 'Português', localName: 'Portuguese' },
  { code: 'pt-BR', name: 'Português (Brasil)', localName: 'Portuguese (Brazil)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', localName: 'Punjabi' },
  { code: 'ro', name: 'Română', localName: 'Romanian' },
  { code: 'ru', name: 'Русский', localName: 'Russian' },
  { code: 'sm', name: 'Gagana Sāmoa', localName: 'Samoan' },
  { code: 'gd', name: 'Gàidhlig', localName: 'Scottish Gaelic' },
  { code: 'sr', name: 'Српски', localName: 'Serbian' },
  { code: 'sn', name: 'Shona', localName: 'Shona' },
  { code: 'sd', name: 'سنڌي', localName: 'Sindhi' },
  { code: 'si', name: 'සිංහල', localName: 'Sinhala' },
  { code: 'sk', name: 'Slovenčina', localName: 'Slovak' },
  { code: 'sl', name: 'Slovenščina', localName: 'Slovenian' },
  { code: 'so', name: 'Soomaali', localName: 'Somali' },
  { code: 'es', name: 'Español', localName: 'Spanish' },
  { code: 'su', name: 'Basa Sunda', localName: 'Sundanese' },
  { code: 'sw', name: 'Kiswahili', localName: 'Swahili' },
  { code: 'sv', name: 'Svenska', localName: 'Swedish' },
  { code: 'tl', name: 'Tagalog', localName: 'Tagalog' },
  { code: 'tg', name: 'Тоҷикӣ', localName: 'Tajik' },
  { code: 'ta', name: 'தமிழ்', localName: 'Tamil' },
  { code: 'tt', name: 'Татар', localName: 'Tatar' },
  { code: 'te', name: 'తెలుగు', localName: 'Telugu' },
  { code: 'th', name: 'ไทย', localName: 'Thai' },
  { code: 'tr', name: 'Türkçe', localName: 'Turkish' },
  { code: 'tk', name: 'Türkmen', localName: 'Turkmen' },
  { code: 'uk', name: 'Українська', localName: 'Ukrainian' },
  { code: 'ur', name: 'اردو', localName: 'Urdu' },
  { code: 'ug', name: 'ئۇيغۇرچە', localName: 'Uyghur' },
  { code: 'uz', name: 'Oʻzbek', localName: 'Uzbek' },
  { code: 'vi', name: 'Tiếng Việt', localName: 'Vietnamese' },
  { code: 'cy', name: 'Cymraeg', localName: 'Welsh' },
  { code: 'xh', name: 'isiXhosa', localName: 'Xhosa' },
  { code: 'yi', name: 'ייִדיש', localName: 'Yiddish' },
  { code: 'yo', name: 'Yorùbá', localName: 'Yoruba' },
  { code: 'zu', name: 'isiZulu', localName: 'Zulu' },
];

if (typeof globalThis !== 'undefined') {
  globalThis.languageData = languageData;
}
